### ISSUE TITLE
Running the Linux\containers-tutorial on a sfonebox fails

### ISSUE THREAD

**Issue by user1m** [Azure-Samples/service-fabric-containers#17]
Running `./install.sh`

I get the following...

```
(FABRIC_E_FILE_NOT_FOUND) The Application Manifest file 'Voting/ApplicationManifest.xml' is not found in the store.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python2.7/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 2696, in provision_application_type
    raise models.FabricErrorException(self._deserialize, response)
FabricErrorException: (FABRIC_E_FILE_NOT_FOUND) The Application Manifest file 'Voting/ApplicationManifest.xml' is not found in the store.
(FABRIC_E_APPLICATION_TYPE_NOT_FOUND) Application type and version not found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python2.7/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python2.7/site-packages/sfctl/custom_app.py", line 251, in create
    client.create_application(app_desc, timeout)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 3158, in create_application
    raise models.FabricErrorException(self._deserialize, response)
FabricErrorException: (FABRIC_E_APPLICATION_TYPE_NOT_FOUND) Application type and version not found
```

**System**:

- Mac running Docker `microsoft/service-fabric-onebox`
- `sfctl` - v3.0.0
- `microsoft/service-fabric-onebox` - v 6.0

**Comment by User1m** [comment]
Non issue - was happing b/c I did not connect `sfctl` to cluster prior to trying to run the `./install.sh`. Would recommend adding that to the `./install.sh` script

**Comment by ciiiii** [comment]
How did u solve this problem, I think i have the same one now.

**Comment by user1m** [comment]
@ciiiii My issue was that I wasn't connected to the cluster via `sfctl`. I needed to run `sfctl cluster select --endpoint localhost:19080` before  the install script. Related: https://github.com/Azure-Samples/service-fabric-containers/pull/19

**Comment by ciiiii** [comment]
Thank u, I did so all the time, but i made it in Ubuntu, problem only in Mac.
